config/routes.rb
Rails.application.routes.draw do
	resources :products, param: :slug
	resources :reviews, param: :slug
	resources :posts, param: :slug
	resources :comments, param: :slug
	resources :images, param: :slug
	get 'product' => 'products#product'
	get 'community' => 'posts#community'
	get 'post' => 'posts#post'
	get 'profiles/*slug' => 'profiles#show'
	post 'select_avatar/*slug' => 'profiles#select_avatar'
	post 'remove_avatar' => 'profiles#remove_avatar'
	get 'login', to: 'logins#new'
	get 'login/create', to: 'logins#create', as: :create_login
	put 'logout' => 'logins#logout'
	put 'settings' => 'logins#settings'
	get 'notifications' => 'notifications#notifications'
	get 'scan_products' => 'products#scan_products', :defaults => { :format => 'json' }
	post 'add_review/*slug' => 'reviews#add_review', :defaults => { :format => 'json' }
	post 'rate_review/*review/*score' => 'feedback#rate_review', :defaults => { :format => 'json' }
	post 'favorite/*product' => 'favorites#favorite', :defaults => { :format => 'json' }
	post 'unfavorite/*product' => 'favorites#unfavorite', :defaults => { :format => 'json' }
	post 'add_comment/*post' => 'comments#add_comment', :defaults => { :format => 'json' }
	post 'reply_comment/*replying_to' => 'comments#reply_comment', :defaults => { :format => 'json' }
	post 'upvote/*object' => 'upvotes#upvote', :defaults => { :format => 'json' }
	post 'unvote/*object' => 'upvotes#unvote', :defaults => { :format => 'json' }
	post 'upload' => 'images#upload', :defaults => { :format => 'json' }
	post 'hide' => 'admin#hide'
	post 'scramble' => 'admin#scramble', :defaults => { :format => 'json' }
	post 'feature' => 'admin#feature'
	post 'promote' => 'admin#promote'
	get 'authy' => 'admin#authy'
    put 'unlock' => 'admin#unlock'
    get 'export' => 'admin#export'
    get 'notification_settings/*slug' => 'notifications#notification_settings'
    post 'update_notification_settings/*slug' => 'notifications#update_notification_settings'
    post 'broadcast' => 'admin#broadcast'
    namespace :marketing do
		get 'instacart' => 'campaigns#instacart'
	end
    get 'about' => 'pages#about'
    get 'stats' => 'admin#stats'
	root 'pages#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
		@user = User.find_by_pretty_slug(params[:slug])
		if "#{params[:view]}" == "Favorites"
			@favorites = @user.favorites.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
		elsif "#{params[:view]}" == "Posts"
			@posts = @user.posts.where.not(role: "Hidden").order("created_at DESC").paginate(:page => params[:page], :per_page => 6)

		else
			@reviews = @user.reviews.where.not(role: "Hidden").order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
		end
		@avatars = []
		if @current_user
			if @user == @current_user
				@avatars = Avatar.where.not(role: "Hidden").order("created_at ASC")
			end
		end
		respond_to do |format|
		  format.html
		  format.js
		end
	end
	def select_avatar
		@avatar = Avatar.find_by_slug(params[:slug])
        if @current_user.image.attached?
        	@current_user.image.purge_later
        end
        @current_user.image.attach(@avatar.img.blob)
        @current_user.img_key = @avatar.img.blob.key
        @current_user.save
        redirect_back fallback_location: root_path
	end
	def remove_avatar
		@current_user.image.purge_later
		@current_user.img_key = nil
		@current_user.save
		redirect_back fallback_location: root_path
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_avatars.html.erb
<!-- Modal -->
<div class="modal fade" id="setAvatar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="myModalLabel">Pick an avatar</h3>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
        </div>
        <div class="modal-body">
            <% @avatars.each do |avatar| %>
            <%= link_to "/select_avatar/#{avatar.slug}", style:"display:inline;text-decoration:none;", method: :post do %>
                <span class="fade-in">
                  <div class="medium" style='background-image: url(<%= avatar.img_url %>); width:90px; height:90px; display:inline-block;'></div>
                </span>
              <% end %>
            <% end %>
            <br />
            <br />
            <%= link_to "Reset avatar", "/remove_avatar", class:"btn btn-light", method: :post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_empty.html.erb
<div style="width:200px;margin-left:20px;text-align:center;">
	<br />
	<strong>Nothing here yet...</strong>
	<br />
	<%= image_tag "oats_bowl.svg", style: "display:block;width:100px;margin-left:60px;margin-top:40px;margin-bottom:60px;" %>
	<br />
	<br />
</div>

app/views/profiles/_favorite.html.erb
<div id="favorite_<%= favorite.product.slug %>" style="margin-bottom:15px;">
	<div class="card">
		<div class="card-block">
			<a href="/products/<%= favorite.product.pretty_slug %>" style="color:#333;text-decoration:none;">
			<%= image_tag "#{favorite.product.img_front_url}", style: "width:100%;height:100%;", class: "pretty" %>
			<div style="padding:5px;">
				<strong>
				<%= favorite.product.name %>
				</strong>
			</div>
			<div style="padding:5px;padding-top:0px;">
				<div style="float:right;margin-right:-10px;">
					<% if @user == @current_user %>
		                <a onClick="removeFromFavorites('<%= favorite.product.slug %>');" style="display:inline-block;float:right;cursor:pointer;color:#CBCBCB;margin-right:10px;margin-tip:-5px;"><i class="fas fa-minus-circle"></i></a>
	                <% end %>
				</div>
				<small style="text-muted"><%= favorite.product.place_name %></small>
			</div>
			</a>
		</div>
	</div>
</div>

app/views/profiles/_notification_settings.html.erb
<!-- Modal -->
<div class="modal fade" id="notificationSettings" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="myModalLabel">Notification Settings</h3>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
        </div>
        <div class="modal-body">
          <div style="margin-bottom:15px;">
           Send me emails about:
         </div>
           <% if @current_user.unread_notifications_batch_emails %>
           <input type="checkbox" id="unread_notifications" name="unread_notifications" value="unread_notifications" checked>
           <% else %>
           <input type="checkbox" id="unread_notifications" name="unread_notifications" value="unread_notifications">
           <% end %>

<label for="unread_notifications"> Unread notifications (once or twice a week)</label><br>
<% if @current_user.featured_batch_emails %>
<input type="checkbox" id="featured_notifications" name="featured_notifications" value="featured_notifications" checked>
<% else %>
<input type="checkbox" id="featured_notifications" name="featured_notifications" value="featured_notifications">
<% end %>
<label for="featured_notifications"> The product of the week (once a week)</label><br>
           <br />
           <div class="alert alert-warning" role="alert" id="status" style="display:none;">Settings updated!</div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
function updateNotificationSettings(role, value) {
    $.ajax({
    url: '/update_notification_settings/' + '<%= @current_user.slug %>',
    type: "POST",
    dataType: "json",
    data : {role: role,
      value: value
    },
    success: function (data) {
      if (data["status"] == "success") {
        $("#status").show();
            function hideStatus(){ 
                $("#status").fadeOut();
            };
            setInterval(hideStatus, 4000);
     };
  }
  });
}
$(document).ready(function() {
    var selected_val = false;
    $('#unread_notifications').change(function() {
        if(this.checked) {
            selected_val = true;
        } else {
          selected_val = false;
        }
        updateNotificationSettings('notifications', selected_val);      
    });
});
$(document).ready(function() {
    var selected_val = false;
    $('#featured_notifications').change(function() {
        if(this.checked) {
            selected_val = true;
        } else {
          selected_val = false;
        } 
        updateNotificationSettings('featured', selected_val);         
    });
});
</script>

app/views/profiles/_prompt_auth.html.erb
<!-- Modal -->
<div class="modal fade" id="promptAuth" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="myModalLabel">Login to Post</h3>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
        </div>
        <div class="modal-body">
          Yay! We'd love to have you contribute, all you need to do is signup/login.
          <br />
          <br />
          <%= google_auth_button proceed_to: create_login_url %>
          </div>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_review.html.erb
<div class="row">
	<div class="col-8">
		<span style="float:right;">
			<% review.rating.times do %>
			  <i class="fas fa-utensil-spoon" style="color:#6BCC00;"></i>
			<% end %>
			<strong><%= review.rating %></strong>
		</span>
		<div style="display:block;margin-top:-15px;margin-bottom:15px;">
		<span class="fade-in">
			<div class="medium" style='background-image: url(<%= review.user.img %>); width:60px; height:60px; display:inline-block;margin-bottom:-20px;'></div>
		</span>
		<div style="display:inline-block;margin-top:20px;"><strong><a href="/profiles/<%= review.user.pretty_slug %>" style="color:#333;text-decoration:none;cursor:pointer;"><%= review.user.name %></a> <%= badge(review.user, 'small') %></strong></div>
		</div>
		  <p><%= review.description %></p>
		  <div class="row">
		    <div class="col-12">
		      <% if review.helpful_count > 0 %>
			      <strong><span id="<%= review.slug %>"><%= review.helpful_count %></span> people found this review helpful.</strong>
		      <% end %>
		    </div>
		  </div>
		  <br />
			</div>
			<div class="col-4">
				<a href="/products/<%= review.product.pretty_slug %>" style="color:#333;text-decoration:none;">		
							<div class="fade-in">
								<% if review.product.img_front? %>

								<div class="show_on_desktop">
									<div class="recty" style='background-image: url(<%= review.product.img_front_url %>); width:100%; display:inline-block;border-radius:2px;height:160px;'></div>
								</div>
	
								<div class="show_on_mobile">
									<%= image_tag "#{review.product.img_front_url}", style: "width:100%;", class: "pretty" %>
								</div>
								<% end %>
							</div>
							<div style="margin-top:6px;">
								<strong>
								<%= review.product.name %>
								</strong>
							</div>
							<div style="margin-top:-2px;">
								<small style="text-muted"><%= review.product.place_name %></small>					
							</div>
				</a>
		   </div>
</div>
<br />
<br />

app/views/profiles/show.html.erb
<% if !(@play) %>
	<%
		meta :title => "#{@user.name} | Oatmel"
	%>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-md-3">
            <span class="fade-in">
				<div class="medium" style='background-image: url(<%= @user.img %>); width:120px; height:120px; display:inline-block;'></div>
		    </span>
		    <% if @user == @current_user %>
		    	<a data-toggle="modal" data-target="#setAvatar" class="btn btn-light btm-sm" style="cursor:pointer">Edit</a>
		    <% end %>
			<h2><%= @user.name %> <%= badge(@user, "Large") %>
			  <% if @current_user %>
			    <% if @current_user.admin? %>
			      <%= link_to "/hide?role=User&slug=#{@user.slug}", method: :post, :data => {:confirm => 'Are you sure you want to ban this user?'}, style: "font-size:14px;color:#9B9B9B;float:right;" do %>
			        <i class="fas fa-flag"></i>
			      <% end %>
			    <% end %>
			  <% end %>
			</h2>
			<br />
			<div class="list-group">
				<div class="list-group-item list-group-item-action flex-column align-items-start">
					Points <span class="badge badge-info"><%= @user.karma %></span>
				</div>
				<div class="list-group-item list-group-item-action flex-column align-items-start">
					Posts <span class="badge badge-info"><%= @user.post_count %></span>
				</div>
			</div>
			<% if @user == @current_user %>
			<br />
			<a data-toggle="modal" data-target="#notificationSettings" class="btn btn-light" style="cursor:pointer;">Notfication Settings</a>
				<br />
				<br />
				<%= link_to "/logout", method: "PUT", class: "btn btn-light" do %>
					Logout
				<% end %>
			<% end %>
		<br />
		<br />
		</div>
		<div class="col-md-9">
			<div class="list-group">
				<div class="list-group-item list-group-item-action flex-column align-items-start">
					 <% if "#{params[:view]}" == "Favorites" %>
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Reviews">Reviews</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a class="btn btn-default" style="background-color:#FCF9F9;border-color:#E1E1E1;color:#444444;" href="/profiles/<%= @user.pretty_slug %>?view=Favorites">Favorites</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Posts">Posts</a>
				    <% elsif "#{params[:view]}" == "Posts" %>
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Reviews">Reviews</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Favorites">Favorites</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a class="btn btn-default" style="background-color:#FCF9F9;border-color:#E1E1E1;color:#444444;" href="/profiles/<%= @user.pretty_slug %>?view=Posts">Posts</a>
				    <% else %>
				      <a class="btn btn-default" style="background-color:#FCF9F9;border-color:#E1E1E1;color:#444444;" href="/profiles/<%= @user.pretty_slug %>?view=Reviews">Reviews</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Favorites">Favorites</a>
				      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				      <a style="color:#888888;" href="/profiles/<%= @user.pretty_slug %>?view=Posts">Posts</a>
				    <% end %>
				</div>
				<% if "#{params[:view]}" == "Favorites" %>
				<div class="list-group-item list-group-item-action flex-column align-items-start" style="padding:0px;padding-top:12px;" id="profile_holder">
				<% else %>
				<div class="list-group-item list-group-item-action flex-column align-items-start" id="profile_holder">
					<br />
				<% end %>
					<% if "#{params[:view]}" == "Favorites" %>
						<% if @favorites.size > 0 %>
							<div class="bricklayer">
							    <%= render :partial => "profiles/favorite", :collection => @favorites, :as => :favorite %>
							</div>
							<div style="display:none;">
								<%= will_paginate @favorites %>
							</div>
						<% else %>
							<%= render 'profiles/empty' %>
						<% end %>
					<% elsif "#{params[:view]}" == "Posts" %>
						<% if @posts.size > 0 %>
							<div id="profile_posts" data-no-turbolink="true">
								<%= render :partial => "posts/post", :collection => @posts, :as => :post %>
							</div>
							<div style="display:none;">
								<%= will_paginate @posts %>
							</div>
						<% else %>
							<%= render 'profiles/empty' %>
						<% end %>
					<% else %>
						<% if @reviews.size > 0 %>
							<div id="profile_reviews" data-no-turbolink="true">
								<%= render :partial => "profiles/review", :collection => @reviews, :as => :review %>
							</div>
							<div style="display:none;">
								<%= will_paginate @reviews %>
							</div>
						<% else %>
							<%= render 'profiles/empty' %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<br />
<br />
<script>
function removeFromFavorites(product_id) {
  $.ajax({
    url: '/unfavorite/' + product_id,
    type: "POST",
    dataType: "json",
    success: function (data) {
      if (data["status"] == "success") {
        $("#favorite_" + product_id).fadeOut(500);
	   };
	}
  });
}
</script>
<style>
@media only screen and (min-width:2px) {
  .bricklayer-column-sizer {
    width: 50%;
  }
}
@media only screen and (min-width:700px) {
  .bricklayer-column-sizer {
    width: 25%;
  }
}
.bricklayer-column {
	padding-left: 7px;
	padding-right: 7px;
}
</style>
<script>
var bricklayer = new Bricklayer(document.querySelector('.bricklayer'));
</script>
<script>
	$(window).unbind("scroll");
  $(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() > $(document).height() - 200) {
       var url;
      url = $('.pagination .next_page').attr('href');
      if (url) {
        $('.pagination').text(" ");
        return $.getScript(url);
      }
    return $(window).scroll();
   }
});
</script>

app/views/profiles/show.js.erb
<% if @favorites %>
	var new_node = jQuery.parseHTML('<%= j render :partial => "profiles/favorite", :collection => @favorites, :as => :favorite %>');
	bricklayer.append(new_node);
	<% if @favorites.next_page %>
	  $('.pagination').replaceWith('<%= j will_paginate(@favorites) %>');
	<% else %>
	  $('.pagination').remove();
	<% end %>
<% elsif @posts  %>
	$('#profile_posts').append('<%= j render :partial => "posts/post", :collection => @posts, :as => :post %>');
	<% if @posts.next_page %>
	  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
	<% else %>
	  $('.pagination').remove();
	<% end %>
<% elsif @reviews %>
	$('#profile_reviews').append('<%= j render :partial => "profiles/review", :collection => @reviews, :as => :review %>');
	<% if @reviews.next_page %>
	  $('.pagination').replaceWith('<%= j will_paginate(@reviews) %>');
	<% else %>
	  $('.pagination').remove();
	<% end %>
<% end %>